version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.5.5
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make test
  publish_to_pypi:
    docker:
      - image: circleci/python:3.5.5
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r twine
      - run:
          command: |
            . venv/bin/activate
            make publish

workflows:
  version: 2
  test_and_publish_to_pypi:
    jobs:
      - test
      - publish_to_pypi:
          requires:
            - test
          filters:
            branches:
              only: master
